### PR TITLE
Implement nAn1 formula notation

### PR DESCRIPTION
**Pull request by HactarCE**
- [x] Update Docs
- [x] Update Visual
- [x] Update Formaulas Ref
- [x] Update Examples
CleanShot 2023-03-10 at 15 44 23@2x

### CODE REVIEW

**Comment by davidkircos** [comment]
@davidfig looks pretty good. I think we intended to start at nA instead of bB for negative though.
CleanShot 2023-03-12 at 19 54 23@2x

**Comment by davidfig** [comment]
Yup. Fixed:

Screenshot 2023-03-12 at 7 36 03 PM

**Comment by davidkircos** [comment]
> I've updated all the text I could find in the docs (Formulas and Overview pages) so I think the images in Overview are all that's left

@jimniels can update these

**Comment by jimniels** [comment]
Docs have been updated with new imagery https://docs.quadratichq.com/overview

**Review by davidkircos — APPROVED** [review]

**Review by jimniels — APPROVED** [review]
LGTM 👍

**Pull request merged**
