### PR TITLE
Combination of Wrap Text and Fit numbers PRs

### LINKED ISSUE #1227: Resize rows and wrap text vertically
- [ ] resize rows
- [ ] optional wrap text vertically
- [ ] double click corner of vertical heading to automatically size row to largest wrapped content
- [ ] align text vertically (top, center, bottom)

### LINKED ISSUE #1460: bug: resizing issues
See video:

https://github.com/quadratichq/quadratic/assets/1316441/700e77a0-b31b-477e-a097-5aa5369ed0ac

### LINKED ISSUE #1463: Bug: formatting not working right on resizing columns
CleanShot 2024-06-25 at 10 56 24

### LINKED ISSUE #1468: Default numbers don't fit in cells
Image

### PR DESCRIPTION
**Pull request by davidfig**
This is a combination of @AyushAgrawal-A2 's Wrap Text PR and the @davidfig 's Fit Numbers PR

# feat: wrap text, align text vertically and auto resize row

closes #1227 
closes #1460 
closes #1463

Changes:
- [x] Cell Label - Wrap, Clip & Overflow
- [x] Cell Label - Vertical Align
- [x] Inline Editor - Same text rendering as cell format (horizontal align, vertical align and wrapping)
- [x] Re-wrap text on cell width change 
- [x] Auto row resize for wrapped text - on cell width change or content change
- [x] Double click on row heading to auto adjust row height
- [x] Fixed bugs related to neighbouring hash position and clipping
- [x] Update clipboard for vertical align
- [x] Multiplayer sync after transient / auto resize
- [x] Store manual / auto resize state. Disable auto resize for manually resized rows.
- [x] Auto resize column (on column heading dbl click) should resize to unwrapped text width.
- [x] Tests 

# Fit numbers

Change how numbers render. In Excel and Sheets, the numbers never overflow the cell. They either reduce their precision, change to scientific, or show up as ####. Fixes #1468.

- [x] redo how CellValue::Number.to_display() works (removing formatting)
- [x] keep some formatting within Rust (but outside the to_display function) so we can still search against what will likely be the displayed number
- [x] move all number formatting from Rust to TS :( - this is necessary b/c we don't know how to stringify the number until we are actually rendering and can compare glyph sizes to the cell width
- [x] move tests from Rust to TS for number rendering
- [x] show #### when number overflows content
- [x] figure out when to change the display from number to scientific to show larger numbers in a smaller space
- [x] fix search to use actual display value (ie, put back the rust to_display w/options for search purposes)

### CODE REVIEW

**Comment by davidfig** [comment]
@AyushAgrawal-A2 I noticed that when vertically centered, the text alignment is a bit off when shrunk to its minimum. See image below.

Screenshot 2024-07-20 at 6 03 00 AM

**Comment by AyushAgrawal-A2** [comment]
@davidfig 
This branch is missing some of the commit, where I restructured code and added tests
Last commit from me here is `cleanup css` [a08a23f](https://github.com/quadratichq/quadratic/pull/1406/commits/a08a23f54c60aa7d7410f7f4dad0d45ccf761713)

Following commits are missing, which should fix code coverage as well
image

**Comment by davidfig** [comment]
Good catch. I'll cherry pick the changes.

**Comment by davidfig** [comment]
I cherry picked the changes. There are a few failing tests. @AyushAgrawal-A2 can you take a look? The failures are probably my fault, but I don't understand the code well enough to fix it.

**Comment by AyushAgrawal-A2** [comment]
> @AyushAgrawal-A2 I noticed that when vertically centered, the text alignment is a bit off when shrunk to its minimum. See image below. The vertically centered one should look like the normal one at that size. (The "hello" is the one with the vertical settings.)
> 
> Screenshot 2024-07-20 at 6 03 00 AM

@davidfig 
this happens because there is extra space to account for `textureHeight` of different characters
if `textureHeight` of all characters in string is less than cell height, then vertical align has room to slight move it
image

**Comment by AyushAgrawal-A2** [comment]
> I cherry picked the changes. There are a few failing tests. @AyushAgrawal-A2 can you take a look? The failures are probably my fault, but I don't understand the code well enough to fix it.
> 
> Not sure if you can make changes to this PR. If not, create a new one and I'll merge it into this one.

@davidfig
I have raised a pr to fix bugs #1574

**Comment by davidfig** [comment]
Code coverage looks good!

**Review by jimniels — DISMISSED** [review]
I have not fully tested the functionality. This is purely a review of the UI:

**Icons**

We're mirroring Google docs for the text wrap icons, I think we should do the same for the vertical alignment buttons. Instead of the Figma-esque icons we have now

CleanShot 2024-07-22 at 11 06 34@2x

Let's use the same ones Google-docs uses. These should be available from MUI:

CleanShot 2024-07-22 at 10 24 49@2x


**Icon state**

I know that today we're not representing the state of the current cell's formatting in the icons, but now that we have these drop-downs I think we should.

For example, if you change the text alignment to center, the dropdown's icon should be the center icon

CleanShot 2024-07-22 at 11 08 18@2x

At minimum, I think we should do this for the dropdown menus.

Later we could apply it to other items in the menu (like bold, italic, etc). But for now, I think we should do it for these new drop-downs.

---

Note: I pushed a commit that updated the border radius of the buttons (as single-icon buttons were circles, but drop-down were ovals, which was odd). Now they're all squares/rectangles to accommodate the different widths.

image

**Comment by AyushAgrawal-A2** [comment]
@jimniels 
I have raised a PR #1581 having both these changes for floating context menu.
It also clears merge conflicts with main.

**Review by davidkircos — CHANGES_REQUESTED** [review]
This works really well! 

Feedback
- Shift enter should add a new line to the cell while using the inline editor
- Precision is displayed as 0s for a number larger than the default column with (see image)
CleanShot 2024-07-22 at 15 35 37@2x

**Comment by AyushAgrawal-A2** [comment]
@davidfig 
> Precision is displayed as 0s for a number larger than the default column with (see image)

can you please take a look at this part

**Comment by davidfig** [comment]
Large numbers have better precision:

Screenshot 2024-07-23 at 4 41 18 AM

**Comment by davidkircos** [comment]
Noticing
- For some reason, the Python cell reference here is not updating the other cells.
- There is a flashy glitchy looking re render when updating array outputs 
Both are shown in this video


https://github.com/user-attachments/assets/242a1d40-4c96-4ba6-9e85-7012ea306f79

**Comment by AyushAgrawal-A2** [comment]
@davidkircos 
Fixed above bugs.

Mulitple async operation were not able to run in a single transaction as the same boolean flag `has_async` was used to flag all async operation in transaction. First async call that finishes would remove that flag and end the transaction. Hence transactions were not executing properly.

Now `has_async` is a counter.

**Comment by davidfig** [comment]
Can you add tests for the multiple async. Any problems with the counter?

**Comment by AyushAgrawal-A2** [comment]
> Can you add tests for the multiple async. Any problems with the counter?

@davidfig 
done

**Review by davidkircos — CHANGES_REQUESTED** [review]
Bolding text and reloading is not preserved 

https://github.com/user-attachments/assets/7aa0f8ea-9477-4c2b-bcb0-1e8b8b2b5f4b

**Comment by AyushAgrawal-A2** [comment]
> Bolding text and reloading is not preserved

@davidkircos 
fixed
another bug due to change in async transaction. I was updating the transaction clone but not saving it back in aync transactions.

**Review by davidkircos — APPROVED** [review]

**Pull request merged**
