### PR TITLE
Fix typo in default spreadsheets

### PR DESCRIPTION
**Pull request by bartbroere**

### CODE REVIEW

**Review by davidkircos — APPROVED** [review]

**Comment by davidkircos** [comment]
Hey, @bartbroere I am not exactly sure what typos you fixed. But this branch looks good to me

**Comment by davidkircos** [comment]
@bartbroere  can you pull `main` into your branches? I couldn't get the tests to run, it was an issue in my github config yaml files. Should be fixed in `main`

**Comment by bartbroere** [comment]
> @bartbroere can you pull `main` into your branches?

Of course, it's done.

> Hey, @bartbroere I am not exactly sure what typos you fixed.

It substitutes the word "mulitple" with "multiple", but it's a bit hard to spot since it's all in one line.

**Comment by davidkircos** [comment]
Great. Feel free to merge

**Comment by bartbroere** [comment]
> Great. Feel free to merge

I would like to, but despite the approved PR I don’t think I have that permission.

**Comment by davidkircos** [comment]
What does the PR show? 

Thanks for debugging this process with me, it should be very smooth once we iron out the issues.

**Comment by davidkircos** [comment]
It seems like the generally accepted way is to have our team merge PRs from the community. Ok I can merge it!

**Pull request merged**
