### PR TITLE
fix: sheet bar dropdown

### PR DESCRIPTION
**Pull request by jimniels**
Fixes the sheet bar dropdown to use shadcn components (instead of szh-menu), so it now supports dark mode and brings it inline with other UI elements. Also fixes it so after sheet actions run the grid receives focus.

### CODE REVIEW

**Comment by jimniels** [comment]
This needs a fix for #1938 which causes really weird dragging issues. Would also be nice to fix it so choosing a color isn't part of the "dragging" interface for the dropdown.

https://github.com/user-attachments/assets/14319110-58b5-40cc-a615-f63f1167de8b

cc @davidfig or @AyushAgrawal-A2 could you take a look?

**Comment by AyushAgrawal-A2** [comment]
>This needs a fix for #1938 which causes really weird dragging issues. Would also be nice to fix it so choosing a color isn't part of the "dragging" interface for the dropdown.

done

**Review by davidkircos — CHANGES_REQUESTED** [review]
Rename button on the menu doesn't work. It loses focus immediately

Move left and move right also don't work

**Review by davidkircos — APPROVED** [review]
lgtm!

**Pull request merged**
