### PR TITLE
Border fixes

### PR DESCRIPTION
**Pull request by davidfig**
- [x] fix clear border (both the color and the button)
- [x] reimplement toggling borders so if you apply the same border to the entire selection, then it clears it instead of setting it

### CODE REVIEW

**Comment by AyushAgrawal-A2** [comment]
Found this bug:
Prod:

https://github.com/user-attachments/assets/a7295e6c-5675-4bec-bbc9-6d2ffd49718c

This PR:


https://github.com/user-attachments/assets/661632c8-d3af-44f9-9bc5-884f772d6f36

**Review by ddimaria — APPROVED** [review]

**Comment by davidfig** [comment]
@AyushAgrawal-A2 I can't replicate the above video in this branch.

**Comment by davidfig** [comment]
@AyushAgrawal-A2 The bug above should be fixed. Please check.

**Comment by AyushAgrawal-A2** [comment]
@davidfig 
still toggle not working for some options

[Screencast from 2024-10-07 22-44-22.webm](https://github.com/user-attachments/assets/0ff4d595-fa06-4773-88cf-98f5eed785f5)

**Comment by davidfig** [comment]
@AyushAgrawal-A2 I think I fixed all cases for toggle. Please take a look.

**Review by AyushAgrawal-A2 — APPROVED** [review]

**Pull request merged**
