### PR TITLE
Next offsets typescript

### PR DESCRIPTION
**Pull request by davidfig**
- [x] create screen -> grid functions for offsets
- [x] TS support for rust offsets
- [x] resize column/row
- [x] double-click to resize column to max size
- [x] select all, column, row
- [x] keyboard arrows and ctrl/meta + arrow     
- [x] separate rust bounds and add tests 
- [x] negative resizing 

Bugs:

- [x] When right-aligned text overlaps the next cell a little bit (image below)
- [x] Disable row resizing for now? We don't support line breaks currently, anyhow.
- [x] Clicking a column header, moves the viewport to the bottom of that column when it selects the cells. Should not move the viewport at all? (see https://quadratichq.slack.com/archives/C03VC0Q1MPA/p1695668370545229)

image

### CODE REVIEW

**Comment by jimniels** [comment]
🐞 There's some funniness going on with the y-axis row heading.

For some reason, it doesn't render the label sometimes. And the selection doesn't match where your selection is on the grid. It'll move if you go in the negative/positive direction, but never beyond 1/-1

https://github.com/quadratichq/quadratic/assets/1316441/0c2d7ae8-3f36-4db7-8bcf-419b6c435388

**Comment by jimniels** [comment]
🐞 Ability to resize a row is gone? I can never get the resize cursor when I hover the line between rows

Sep-25-2023 13-56-09

**Comment by jimniels** [comment]
🐞 Edit a column of text and then try to resize it. When you resize, truncating the text at the overflow doesn't happen. Only once you then edit the cell again does it then apply the overflow.

Sep-25-2023 13-59-48

**Comment by jimniels** [comment]
Not sure if this is expected, but clicking to select a column with no data in it results in an error being logged in the console every time you click
CleanShot 2023-09-25 at 14 35 32

**Comment by davidfig** [comment]
> 🐞 Edit a column of text and then try to resize it. When you resize, truncating the text at the overflow doesn't happen. Only once you then edit the cell again does it then apply the overflow.
> 
> Sep-25-2023 13-59-48 [ Sep-25-2023 13-59-48 ](https://user-images.githubusercontent.com/1316441/270459091-2e3840c9-1564-4aa7-a2bb-3cd62fadf237.gif) [ ](https://user-images.githubusercontent.com/1316441/270459091-2e3840c9-1564-4aa7-a2bb-3cd62fadf237.gif)

@jimniels I can't seem to replicate this one. Can you provide steps?

**Comment by jimniels** [comment]
> I can't seem to replicate this one. Can you provide steps?

@davidfig It seems to be something that only occurs in the negative region?

If i create a new document and put text in cells (in positive quadrant) things work as expected.

But then when i enter similar values in the negative quadrant and resize, i get the no-cropping text issue.

See video:

https://github.com/quadratichq/quadratic/assets/1316441/77e0f3d5-fbf7-4d9e-ac5b-4b2b8b5d1f32

**Pull request merged**
