### PR TITLE
fix: meta+shift+select is off by 1

### LINKED ISSUE #1375: bug: shift select is off by 1
CleanShot 2024-05-21 at 20 40 35

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
closes #1375

[meta_shift_select_bug.webm](https://github.com/quadratichq/quadratic/assets/54364088/badcff07-c53f-4301-b010-b17a6f631aad)

### CODE REVIEW

**Comment by davidkircos** [comment]
This works great! The only issue i've noticed is that when pressing command + control + left multiple times the behavior changes when it hits the edge of the content in the document. It should continue to go left, instead once at the edge it goes back and forth.

See video: I am just repeadily hitting command + control + left


https://github.com/quadratichq/quadratic/assets/3479421/61eb1efa-dc6a-42a2-a392-7239cdf0b14f

**Review by davidkircos — CHANGES_REQUESTED** [review]
This works great! The only issue i've noticed is that when pressing command + control + left multiple times the behavior changes when it hits the edge of the content in the document. It should continue to go left, instead once at the edge it goes back and forth.

See video: I am just repeadily hitting command + control + left


https://github.com/quadratichq/quadratic/assets/3479421/61eb1efa-dc6a-42a2-a392-7239cdf0b14f

**Comment by AyushAgrawal-A2** [comment]
@davidkircos 

Done
[fix_edgecase.webm](https://github.com/quadratichq/quadratic/assets/54364088/618bfcde-18a3-4eee-994e-a4e349248b3f)

**Comment by davidkircos** [comment]
@AyushAgrawal-A2 thanks for the fix! 

I think it'd be worth adding some tests here considering it's pure rust.

**Comment by AyushAgrawal-A2** [comment]
> @AyushAgrawal-A2 thanks for the fix!
> 
> I think it'd be worth adding some tests here considering it's pure rust.

@davidkircos 
Done

**Comment by davidkircos** [comment]
Thanks for the fix, this is great!

**Pull request merged**
