### PR TITLE
Simple file storage

### PR DESCRIPTION
**Pull request by ddimaria**
- [x] Implement file-system storage in quadratic-rust-shared and quadratic-files
- [x] Implement file-system storage in quadratic-api and quadratic-client

On the API side, you denote the storage method as an env var: STORAGE_TYPE=file-system # s3 or file-system.  There is a storage abstraction within API that can switch between S3 and FileSystem.  The abstracted functions are:
* `getFileUrl()`
* `getPresignedFileUrl()`  (reuse ENCRYPTION_KEY for uuid encryption in presigned URLs)
* `uploadFile()`
* `uploadMiddleware()` (express middleware for S3 and FileSystem

On the File Service side, the same env var STORAGE_TYPE is used to turn on a few new routes:
* `GET /storage/:key` Get any file in storage, validated by JWT
* `POST /storage/:key` Upload any file in storage, validated by JWT
* `GET /storage/presigned/:key` Get any file in storage via a presigned key, validated by key decryption

**Environment Variables to Add:**

quadratic-api
```env
STORAGE_TYPE=s3 # s3 or file-system
QUADRATIC_FILE_URI=
```
quadratic-files
```env
STORAGE_TYPE=s3 # s3 or file-system
STORAGE_DIR=
STORAGE_ENCRYPTION_KEYS=
```

### CODE REVIEW

**Comment by davidkircos** [comment]
@ddimaria has merge conflicts

**Review by davidkircos — CHANGES_REQUESTED** [review]
Breaks S3 on hosted preview branches and production because of headers preventing auth being passed to the s3 request on a different domain.

**Comment by AyushAgrawal-A2** [comment]
> Breaks S3 on hosted preview branches and production because of headers preventing auth being passed to the s3 request on a different domain.

It is CORS issue, not related to SharedArrayBuffer, `Allowed-Origin: "*"` is not valid with credentials

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#directives

**Review by AyushAgrawal-A2 — CHANGES_REQUESTED** [review]
S3 works locally

File-System
file is created but not able to open it

image

image

image

**Comment by ddimaria** [comment]
Closing in favor of https://github.com/quadratichq/quadratic/pull/1718

**Pull request closed without merging**
