### PR TITLE
Open code editor added to data menu

### PR DESCRIPTION
**Pull request by davidfig**
Screenshot 2024-06-29 at 6 24 50 AM

### CODE REVIEW

**Review by HactarCE — APPROVED** [review]
Thank you! Yay for accessibility and browser compat!

**Comment by luke-quadratic** [comment]
nit: "Open Code Editor" --> "Open code editor"

**Comment by davidkircos** [comment]
I think it makes sense to add to the Content Menu and the Command Palette 
CleanShot 2024-07-08 at 11 02 26@2x


The data menu feels like an awkward place to me

**Review by davidkircos — CHANGES_REQUESTED** [review]
I think it makes sense to add to the Content Menu and the Command Palette 
CleanShot 2024-07-08 at 11 02 26@2x


The data menu feels like an awkward place to me

**Pull request merged**
