### PR TITLE
feat: wrap text, align text vertically and auto resize row

### LINKED ISSUE #1227: Resize rows and wrap text vertically
- [ ] resize rows
- [ ] optional wrap text vertically
- [ ] double click corner of vertical heading to automatically size row to largest wrapped content
- [ ] align text vertically (top, center, bottom)

### LINKED ISSUE #1460: bug: resizing issues
See video:

https://github.com/quadratichq/quadratic/assets/1316441/700e77a0-b31b-477e-a097-5aa5369ed0ac

### LINKED ISSUE #1463: Bug: formatting not working right on resizing columns
CleanShot 2024-06-25 at 10 56 24

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
closes #1227 
closes #1460 
closes #1463

Changes:
- [x] Cell Label - Wrap, Clip & Overflow
- [x] Cell Label - Vertical Align
- [x] Inline Editor - Same text rendering as cell format (horizontal align, vertical align and wrapping)
- [x] Re-wrap text on cell width change 
- [x] Auto row resize for wrapped text - on cell width change or content change
- [x] Double click on row heading to auto adjust row height
- [x] Fixed bugs related to neighbouring hash position and clipping
- [x] Update clipboard for vertical align
- [x] Multiplayer sync after transient / auto resize
- [x] Store manual / auto resize state. Disable auto resize for manually resized rows.
- [x] Auto resize column (on column heading dbl click) should resize to unwrapped text width.
- [x] Tests

### CODE REVIEW

**Comment by AyushAgrawal-A2** [comment]
@luke-quadratic @davidfig @ddimaria @davidkircos 
This is ready for initial feedback. I am not sure how far I am from desired functionality.

**Comment by davidfig** [comment]
This looks super nice. A few things I noticed on the functionality:

* there's a noticeable difference between the rendered text vs Monaco when wrapping. Probably has to do with the CSS vertical spacing
* the renderer is dropping characters when wrapping the text, mostly on the last line of the text
* it's auto adjusting the height after a user manually adjusted it. Once the height is changed, it should not auto-adjust unless the user double-clicks on the corner of the row heading. It should clip the text if too big instead
* the down arrow on the floating context menu is a bit large (I really like this approach)

**Comment by AyushAgrawal-A2** [comment]
> * it's auto adjusting the height after a user manually adjusted it. Once the height is changed, it should not auto-adjust unless the user double-clicks on the corner of the row heading. It should clip the text if too big instead
@davidfig 
I wanted this also, but I was not sure about implementation.
This requires a flag in schema to denote whether a row height is manually set or set by auto resize. I was unsure if I should add this boolean flag in schema or I can reuse format_rows in your running PR. Or maybe something else...?
Can you please suggest schema entry for this ?

**Comment by davidfig** [comment]
> @davidfig I wanted this also, but I was not sure about implementation. This requires a flag in schema to denote whether a row height is manually set or set by auto resize. I was unsure if I should add this boolean flag in schema or I can reuse format_rows in your running PR. Or maybe something else...? Can you please suggest schema entry for this ?

Can't you rely on undefined for row height? Once it has a value, then use that instead. Or am I missing something?

**Comment by AyushAgrawal-A2** [comment]
> > @davidfig I wanted this also, but I was not sure about implementation. This requires a flag in schema to denote whether a row height is manually set or set by auto resize. I was unsure if I should add this boolean flag in schema or I can reuse format_rows in your running PR. Or maybe something else...? Can you please suggest schema entry for this ?
> 
> Can't you rely on undefined for row height? Once it has a value, then use that instead. Or am I missing something?

@davidfig 
Auto row resizing also sets a value in SheetsOffsets and this value propagates to client and renderer ... so value is defined in both cases whether manual resize or auto.

**Comment by davidfig** [comment]
> Auto row resizing also sets a value in SheetsOffsets and this value propagates to client and renderer ... so value is defined in both cases whether manual resize or auto.
Ah, yes, you're right. 

Maybe we add an auto-resize entry (which is how I think Excel does it). The easiest way would be to add an `auto_size: BTreeMap<i64, f64>` to `Offsets`. The f64 is the current size for that row/column (but changeable based on the actual content for that column/row). We then remove that entry if we manually change the size (which is stored in `sizes`). Alternatively, we can create an enum for sizes for size and autosize. Either way should work. 

It's tricky since we have to update that autosize whenever content is changed, but we only know the wrapped size after we render it. Ideally, columns would also work this way. 

This would be a bunch of work. Feel free to punt on it, and we can work toward merging this PR, and open an issue to do the autosize down the road.

**Comment by AyushAgrawal-A2** [comment]
> This would be a bunch of work. Feel free to punt on it, and we can work toward merging this PR, and open an issue to do the autosize down the road.

@davidfig 
I would try to finish this in this pr itself. I wanted to ask the schema doubt as you guy might have already planned for this. I didn't want to add random entries to schema myself.
This pr will anyways need to be refactored to incorporate changes in your `Select all, column, and row #1363` pr, after it is merged in main.

**Comment by AyushAgrawal-A2** [comment]
> This looks super nice. A few things I noticed on the functionality:
> 
> * there's a noticeable difference between the rendered text vs Monaco when wrapping. Probably has to do with the CSS vertical spacing
> * the renderer is dropping characters when wrapping the text, mostly on the last line of the text
> * it's auto adjusting the height after a user manually adjusted it. Once the height is changed, it should not auto-adjust unless the user double-clicks on the corner of the row heading. It should clip the text if too big instead
> * the down arrow on the floating context menu is a bit large (I really like this approach)

@davidfig 
all done

**Comment by AyushAgrawal-A2** [comment]
@davidfig 
ready for review

**Review by davidfig — CHANGES_REQUESTED** [review]
Thanks for the changes. This is working great, and the code looks good. I liked that you improved some of my spaghetti code as you refactored. Super helpful.

Only comment: please add more unit tests in rust. You have high-level rust tests, but we usually add rust tests for any file we change or add functionality (within reason). 

There's also a way of testing all js.rs functions--you can see examples in the code (`expect_js_call` or `expect_js_call_count`) or reach out if you need help setting it up.

Great job!

**Comment by davidfig** [comment]
Hey Ayush, I was using this branch to build fit-numbers, and it doesn't seem like the vertical alignment is working properly. CellLabel is getting the right verticalAlign value, but I can't find where you use that value to update the y position. Am I missing something?

**Comment by davidfig** [comment]
The horizontal alignment for Monaco does not work consistently. It sometimes places the cursor in weird places compared to the text when alignment is not left.

**Comment by davidfig** [comment]
If we're going to add the horizontal alignment to the editor, we also have to properly support right align. The input box needs to be aligned to the right side of the cell and flow to the left. See:

https://github.com/quadratichq/quadratic/assets/442879/242c6d97-fece-427c-bae9-e8160a066b60

**Comment by AyushAgrawal-A2** [comment]
@davidfig 
I'm sorry, I accidentally deleted the verticalAlign position logic in CellLabel in one of the commits.
Fixed all three bugs, PTAL.

I am still figuring out best way to add test for auto resize. I have currently disabled auto resize in test. This is kind of a side effect which is triggered when cell value / cell formatting changes. When trigger the transaction is put on hold, till a callback from renderer is received having row heights. If I enable it in tests, a lot of other test gets messed up. as there is no callback from renderer.

**Comment by davidfig** [comment]
Cool. Thanks for the fixes.

> When triggered the transaction is put on hold, till a callback from renderer is received having row heights. If I enable it in tests, a lot of other test gets messed up. as there is no callback from renderer.
Maybe change js.rs's test code to automatically call the complete function whenever called in a test. That way you don't have to redo all the other tests, and you always get a known value back.

**Comment by AyushAgrawal-A2** [comment]
Hey @davidfig ,
I think I'll have to modify existing test anyways, to check whether the side effect runs when excepted and should run when it is not suppose to.

Also when modifying test, I saw `run_javascript.rs` has test for python only, same as `run_python.rs` no js test. I guess this pending to be updated.

**Comment by davidfig** [comment]
We do not have a great way of running TS+rust tests. vitest supports it, but I've not been successful in getting it to run consistently. Right now, all the JS and Python tests are run separately from the Rust tests. I think I added additional rust-only run_javascript tests in one of my outstanding PRs. Feel free to try to get TS + WASM to run in vitest. It would be nice to have better tests.

**Review by davidkircos — CHANGES_REQUESTED** [review]
please resolve merge conflicts

**Comment by AyushAgrawal-A2** [comment]
@davidfig 
I have added rust unit tests.
I tried setting up vitest, but it will take time. I will try in a separate PR.

**Review by davidfig — APPROVED** [review]

**Comment by davidfig** [comment]
Please resolve conflicts (hopefully last one)

**Comment by davidfig** [comment]
Ugh. Let me see if I can fix that.

**Pull request closed without merging**
