### PR TITLE
Horizontally scroll with shift + mouse wheel

### PR DESCRIPTION
**Pull request by davidfig**
Implements #177

### CODE REVIEW

**Comment by HactarCE** [comment]
Working perfectly on my end!

**Comment by davidkircos** [comment]
With a trackpad, this inverses the scroll. Is it possible to have this only effect the mouse scroll, not the trackpad?

**Review by HactarCE — APPROVED** [review]

**Review by jimniels — CHANGES_REQUESTED** [review]
Per [David's comment](https://github.com/quadratichq/quadratic/pull/367#issuecomment-1475465233), this appears to affect panning on the trackpad when you hold down shift.

In prod today, if you hold down shift and pan with a trackpad it works the same as if you hold down shift and pan without it.

But with these changes, shift + pan on a trackpad breaks (it sort of pans back and forth just a tiny bit, regardless of the direction you pan)

**Comment by jimniels** [comment]
This is being implemented in #533

**Pull request closed without merging**
